### ISSUE TITLE
The role won't setup oh-my-zsh correctly for root user

### ISSUE THREAD

**Issue by GR360RY** [ctorgalson/ansible-role-oh-my-zsh#23]
The role treats root user as a regular user, hence the oh-my-zsh will be cloned under `/home/root` and not `/root` on linux systems.
I can provide a quick pr the will address the issue. Something along the following lines

```yml
- name: "OMZ | establish home directory for standard user."
  ansible.builtin.set_fact:
    omz_user_home_dir: "{{ (ansible_system == 'Darwin') | ternary('Users', 'home') }}"
  when: omz_user.name != "root"

- name: "OMZ | establish home directory for root user."
  ansible.builtin.set_fact:
    omz_user_home_dir: "{{ (ansible_system == 'Darwin') | ternary('var', '/') }}"
  when: omz_user.name == "root"
```
